#%RAML 1.0 Library

types:
  error:
    type: object
    properties:
      is_success:
        type: boolean
        required: false
      errors:
        type: array
        items:
          type: object
          properties:
            error_code:
              type: string
              required: false
            error_message:
              type: string
              required: false
